name: primeiro-workflow #nome técnico
run-name: Meu Primeiro Workflow # nome descritivo

# on: [push]

# event
on:
    push:
        branches:
            - main
jobs:
    mac:
        runs-on: macos-latest
        steps:
            - name: Rodar um hello no mac
              run: echo "Rodou no mac"
    linux:
        runs-on: ubuntu-latest
        steps:
            - name: Rodar um hello no linux
              run: echo "Rodou no linux tbm"